### ISSUE TITLE
Implementation Questions

### ISSUE THREAD

**Issue by Nornec** [behearn/Hearn.Midi#1]
Hi there,
I'm developing a generative MIDI app called Midinous and there have often been requests to write out MIDI files of the sequences that play. Due to the unpredictable nature of the sequences in Midinous, writing a complete MIDI file all at once (like the example provided) isn't really practical. Ideally I'd like to write to the stream writer as the sequence plays and once the sequence stops, build the MIDI file for use elsewhere. 

Every note that plays in Midinous has a note, velocity, channel, and duration value, but the duration is specified as a decimal so not cleanly tied to a grid. What's more, events can be "off grid" as well, meaning notes may be aligned to fractional numbers like 1.333_ quarter notes.

Do you have any tips to implement Hearn.Midi into my project, or is this not the intended implementation of the library?
Thanks!

**Comment by behearn** [comment]
Hi,

I think it could work.  It works by tracking the current "tick".  The Tick() method has two overloads, one for the note length enum, and also the number of ticks.  There are 96 ticks in a quarter note, so for your 1.333 scenario you would tick 96  * 1.333 ticks = 128 ticks.  As long as you know the duration at the point of writing the note then you just need to call the Tick() method with the number of ticks since the last note on and the next note on (which you'll need to track to pass in).  If it's open ended then you'll need to amend the library to explicitly send the MIDI_EVENT_NOTE_OFF by creating a new WriteNoteOff() or similar function (taking the logic in the Tick method).

I'd love to know if you do manage to use it successfully.

Brian.

**Comment by Nornec** [comment]
I see in the example that the rendering of the song is done as one big concatenation. Can these methods be called independently to increase the length of the stream? If so, I think I could use your suggestion and build to the file as the sequence plays and write it out only at the end.

**Comment by behearn** [comment]
Yes, these are equivalent
```
midiStreamWriter
        .WriteStartTrack()
            .WriteNote(0, MidiNoteNumbers.C4, 127, NoteDurations.WholeNote);
```
and
```
midiStreamWriter.WriteStartTrack();
midiStreamWriter.WriteNote(0, MidiNoteNumbers.C4, 127, NoteDurations.WholeNote);
```
You will need to keep a reference to the midiStreamWriter and call `Dispose()` when done.  The example is scoped within a `using` statement which disposes automatically when complete.

**Comment by Nornec** [comment]
Fantastic! Thank you so much. I'm grabbing the NuGet and I will let you know how this works out.

**Comment by Nornec** [comment]
Your library has worked well, taking the guesswork out of writing MIDI files with an easy-to-use library! I did modify MidiStreamWriter to remove all of the duration and note length logic, including the enums, as I simply didn't need those due to my current implementation, and I added a method for writing note off messages. Closing as satisfied!
